### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lorypelli** [nick747/f_conv_roman#1]
La puoi caricare su github please?

**Comment by gongbhao** [comment]
Il progetto già è caricato (sennò non potevi aprire la issue). Vuoi intendere di caricare l'apk?

**Comment by lorypelli** [comment]
> Il progetto già è caricato (sennò non potevi aprire la issue). Vuoi intendere di caricare l'apk?

Sì, anche su quello nuovo che hai rilasciato se possibile

**Comment by gongbhao** [comment]
L'APK sta nel progetto, lo puoi scaricare andando alla path che ho messo nel readme

**Comment by gongbhao** [comment]
Ho aggiunto il download dell'apk degli assets della release se lo vuoi scaricare
